_target_: src.models.classify4_module.Classify4LitModule

name: vit_large_r50_s32_384

lr: 1e-4
weight_decay: 0.0005
t_max: 10
min_lr: 1e-6
T_0: 15
T_mult: 2
eta_min: 1e-6
pretrained: True
scheduler: 'ReduceLROnPlateau'
factor: 0.5
patience: 3
eps: 1e-8
loss_weight: 0.25
module_type: 'classify4'