_target_: src.models.voting_module.VotingLitModule

name: vit_large_r50_s32_384

lr: 1e-4
pretrained: True
scheduler: 'ReduceLROnPlateau'
threshold: 0.2
num_sample: 10
key: 'ent'
sampling: 'trust'
decide_by_total_probs: False
weighted_sum: False
module_type: 'voting'
seed: 123