# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: colon.yaml # choose the datamodule for evaluation
  - model: newvote.yaml
  - callbacks: test.yaml
  - logger: none.yaml
  - trainer: gpu.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: 42

name: "default"

# passing checkpoint path is necessary
# ckpt_path: "/home/compu/jh/project/colon/logs/runs/2022-02-26/02-35-42/checkpoints/epoch_012.ckpt"
#ckpt_path: "/home/compu/jh/project/colon/logs/runs/2022-01-28/02-49-40/checkpoints/epoch_012.ckpt"
# ckpt_path: "/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-24_05-18-38/checkpoints/epoch_004.ckpt"
ckpt_path: "/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt"