# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: colon.yaml # choose the datamodule for evaluation
  - model: colon.yaml
  - callbacks: wandb.yaml
  - logger: wandb.yaml
#  - logger: null
  - trainer: default.yaml
  - log_dir: evaluation.yaml

  - experiment: null

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: 42

name: "default"

# passing checkpoint path is necessary
ckpt_path: "/home/compu/jh/project/colon/logs/runs/2022-02-26/02-35-42/checkpoints/epoch_012.ckpt"
#ckpt_path: "/home/compu/jh/project/colon/logs/runs/2022-01-28/02-49-40/checkpoints/epoch_012.ckpt"
