_target_: src.datamodules.feature_datamodule.GastricDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 16
num_workers: 0
pin_memory: True
img_size: 384
drop_last: False
data_name: 'gastric'
data_ratio: 1.0