# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classifycompare.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classifycompare.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classifycompare.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=123 model=classifycompare.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classifycompare.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classifycompare.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classifycompare.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='vit_large_r50_s32_384' seed=12 model=classifycompare.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

# python ../train.py model.name='efficientnet_b0' seed=123 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='efficientnet_b0' seed=123 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
# python ../train.py model.name='efficientnet_b0' seed=123 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=123 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='densenet121' seed=123 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=123 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=123 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=123 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='efficientnet_b0' seed=12 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=12 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=12 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=12 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='densenet121' seed=12 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=12 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=12 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=12 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 


python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classifycompare.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classifycompare.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classifycompare.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=1 model=classifycompare.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='efficientnet_b0' seed=1 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=1 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=1 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=1 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='densenet121' seed=1 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=1 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=1 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=1 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

##
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classifycompare.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classifycompare.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classifycompare.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='vit_large_r50_s32_384' seed=2 model=classifycompare.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['compare+classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='efficientnet_b0' seed=2 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=2 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=2 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='efficientnet_b0' seed=2 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 

python ../train.py model.name='densenet121' seed=2 model=classify4.yaml datamodule.data_ratio=0.25 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=2 model=classify4.yaml datamodule.data_ratio=0.5 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=2 model=classify4.yaml datamodule.data_ratio=0.75 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 
python ../train.py model.name='densenet121' seed=2 model=classify4.yaml datamodule.data_ratio=1.0 datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6,7\' datamodule.batch_size=16 


# python ../train.py model=classify4.yaml logger.wandb.project='colon' trainer.devices=[4,5,6,7] datamodule=colon.yaml logger.wandb.tags=['only_classify'] datamodule.batch_size=16 datamodule.num_workers=8 model.scheduler='CosineAnnealingLR'
# python ../test.py model=classifycompare.yaml logger.wandb.project='colon' trainer.devices=[4,5,6,7] datamodule=colon_test2.yaml logger.wandb.tags=['compare+classify','test2'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classify4/2022-08-11_18-04-24/checkpoints/epoch_006.ckpt"
# python ../test.py model=classify4.yaml logger.wandb.project='colon' trainer.devices=[4,5,6,7] datamodule=colon_test2.yaml logger.wandb.tags=['only_classify','test2'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classify4/2022-08-11_18-04-24/checkpoints/epoch_006.ckpt"

# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.2 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.25 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.3 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.35 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.4 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.45 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.5 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.55 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.6 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.65 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.7 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.75 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.8 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.85 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.90 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.95 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=1.0 model.sampling='kmeans'

# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.5 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.55 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.6 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.65 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.7 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.75 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.8 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.85 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.9 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.95 model.sampling='kmeans'
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[6] datamodule=colon.yaml logger.wandb.tags=['kmeans','voting','prob'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=1.0 model.sampling='kmeans'




# python ../test.py model=classifycompare.yaml logger.wandb.project='colon' trainer.devices=[4,5,6] datamodule=colon.yaml ckpt_path='/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt'


