#!/bin/bash
# #colon
# python ../test.py model.name='vit_large_r50_s32_384' datamodule.data_ratio=0.1 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-24_07-58-46/checkpoints/epoch_015.ckpt"
# python ../test.py model.name='vit_large_r50_s32_384' datamodule.data_ratio=0.3 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-24_08-09-59/checkpoints/epoch_011.ckpt"
# python ../test.py model.name='vit_large_r50_s32_384' datamodule.data_ratio=0.5 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-24_08-22-35/checkpoints/epoch_005.ckpt"
# python ../test.py model.name='vit_large_r50_s32_384' datamodule.data_ratio=0.7 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-24_08-33-15/checkpoints/epoch_006.ckpt"
# python ../test.py model.name='vit_large_r50_s32_384' datamodule.data_ratio=0.9 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-24_08-47-15/checkpoints/epoch_006.ckpt"
# #havard
# python ../test.py datamodule.data_ratio=0.1 model=savefeatures.yaml datamodule=havard_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt"
# python ../test.py datamodule.data_ratio=0.3 model=savefeatures.yaml datamodule=havard_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-32-51/checkpoints/epoch_002.ckpt"
# python ../test.py datamodule.data_ratio=0.5 model=savefeatures.yaml datamodule=havard_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-43-38/checkpoints/epoch_003.ckpt"
# python ../test.py datamodule.data_ratio=0.7 model=savefeatures.yaml datamodule=havard_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-58-48/checkpoints/epoch_000.ckpt"
# python ../test.py datamodule.data_ratio=0.9 model=savefeatures.yaml datamodule=havard_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_13-11-40/checkpoints/epoch_003.ckpt"
#prostate
# python ../test.py datamodule.data_ratio=0.1 model=savefeatures.yaml datamodule=prostate_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/vit_large_r50_s32_384/2022-08-23_22-30-01/checkpoints/epoch_006.ckpt"
# python ../test.py datamodule.data_ratio=0.3 model=savefeatures.yaml datamodule=prostate_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/vit_large_r50_s32_384/2022-08-23_22-52-53/checkpoints/epoch_007.ckpt"
# python ../test.py datamodule.data_ratio=0.5 model=savefeatures.yaml datamodule=prostate_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/vit_large_r50_s32_384/2022-08-23_23-28-43/checkpoints/epoch_007.ckpt"
# python ../test.py datamodule.data_ratio=0.7 model=savefeatures.yaml datamodule=prostate_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/vit_large_r50_s32_384/2022-08-24_00-18-37/checkpoints/epoch_004.ckpt"
# python ../test.py datamodule.data_ratio=0.9 model=savefeatures.yaml datamodule=prostate_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/vit_large_r50_s32_384/2022-08-24_01-07-34/checkpoints/epoch_002.ckpt"
#ubc
# vit

# python ../test.py datamodule.data_ratio=0.25 seed=1 model.seed=1 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_00-17-08/checkpoints/epoch_002.ckpt"
# python ../test.py datamodule.data_ratio=0.5 seed=1 model.seed=1 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_00-26-11/checkpoints/epoch_002.ckpt"
# python ../test.py datamodule.data_ratio=0.75 seed=1 model.seed=1 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_00-38-02/checkpoints/epoch_008.ckpt"
# python ../test.py datamodule.data_ratio=1.0 seed=1 model.seed=1 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_01-02-16/checkpoints/epoch_003.ckpt"



# python ../test.py datamodule.data_ratio=0.25 seed=2 model.seed=2 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_04-02-56/checkpoints/epoch_008.ckpt"
# python ../test.py datamodule.data_ratio=0.5 seed=2 model.seed=2 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_04-16-45/checkpoints/epoch_013.ckpt"
# python ../test.py datamodule.data_ratio=0.75 seed=2 model.seed=2 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_04-42-00/checkpoints/epoch_005.ckpt"
# python ../test.py datamodule.data_ratio=1.0 seed=2 model.seed=2 model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/vit_large_r50_s32_384/2022-08-31_05-01-15/checkpoints/epoch_007.ckpt"

python ../test.py seed=42 model.seed=42 model.name='vit_large_r50_s32_384' model=savefeatures.yaml datamodule=colon_feature.yaml logger=none datamodule.num_workers=8 trainer.devices=[3] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt"


