# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit_base_patch16_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit3_base_patch16_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit3_base_patch16_384_in21ft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit3_large_patch16_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit3_large_patch16_384_in21ft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit3_small_patch16_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='deit3_small_patch16_384_in21ft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='swin_base_patch4_window12_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='swin_base_patch4_window12_384_in22k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='swin_large_patch4_window12_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16

# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_nano_12_p8_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_nano_12_p16_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_small_12_p8_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_small_12_p16_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_small_24_p8_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_small_24_p16_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16

# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_tiny_12_p8_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_tiny_12_p16_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_tiny_24_p8_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='xcit_tiny_24_p16_384_dist' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16

# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='mobilevitv2_150_384_in22ft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='mobilevitv2_175_384_in22ft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='mobilevitv2_200_384_in22ft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16


# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='swinv2_base_window12to24_192to384_22kft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='swinv2_large_window12to24_192to384_22kft1k' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='volo_d1_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16
# python ../train.py logger.wandb.project='colon_new' model=only4.yaml datamodule=colon.yaml model.name='volo_d2_384' model.scheduler='CosineAnnealingLR' logger.wandb.tags=['only_classify','no_discriminator'] datamodule.num_workers=8 trainer.devices=\'0,4,5,6,7\' datamodule.batch_size=16

python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.2  model.sampling='random' 
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.25 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.3 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.35 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.4 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.45 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.5 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.55 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.6 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.65 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.7 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.75 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.8 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.85 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.90 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=0.95 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','ent','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='ent' model.threshold=1.0 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.5 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.55 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.6 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.65 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.7 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.75 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.8 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.85 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.9 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=0.95 model.sampling='random'
python ../test.py model.name='densenet121' datamodule.data_ratio=0.9 model=voting.yaml logger.wandb.project='ubc' trainer.devices=[0] datamodule=ubc.yaml logger.wandb.tags=['voting','prob','90%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/densenet121/2022-08-24_17-15-44/checkpoints/epoch_002.ckpt" model.key='prob' model.threshold=1.0 model.sampling='random'