#!/bin/bash
# Shedule execution of many runs
# Run from root folder with: bash scripts/schedule.sh
#python ../test.py ckpt_path="/home/compu/jh/project/colon/logs/runs/2022-01-28/02-49-40/checkpoints/epoch_012.ckpt" datamodule.batch_size=2 datamodule.drop_last=True
#WANDB_START_METHOD=thread python ../test.py -m ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-05-05_03-02-51/checkpoints/epoch_008.ckpt" model.decide_by_total_probs=True,False model.weighted_sum=True,False model.key='prob','ent' model.sampling='random','convinced' model.threshold=0.5,0.55,0.6,0.65,0.7,0.75,0.8,0.85 model.num_sample=10,20,30,40,50
#WANDB_START_METHOD=thread python ../test.py -m ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-05-05_03-02-51/checkpoints/epoch_008.ckpt" model.decide_by_total_probs=True,False model.weighted_sum=True,False model.key='ent' model.sampling='random','convinced' model.threshold=0.9,0.95,1.0 model.num_sample=10,20,30,40,50
# WANDB_START_METHOD=thread python ../train.py -m datamodule=gastric.yaml model=gastric.yaml logger.wandb.project='gastric' model.name='vit_base_patch16_384','vit_base_patch32_384','vit_base_r50_s16_384','vit_large_patch16_384','vit_large_patch32_384','vit_large_r50_s32_384' model.scheduler='ReduceLROnPlateau','CosineAnnealingLR','CosineAnnealingWarmRestarts','StepLR','ExponentialLR' logger.wandb.tags=['only_classification']
#WANDB_START_METHOD=thread python ../train.py -m datamodule=gastric.yaml model=gastric.yaml logger.wandb.project='gastric' model.name='vit_base_patch16_384','vit_base_patch32_384','vit_base_r50_s16_384','vit_large_patch16_384','vit_large_patch32_384','vit_large_r50_s32_384' model.scheduler='ReduceLROnPlateau','CosineAnnealingLR','CosineAnnealingWarmRestarts','StepLR','ExponentialLR' logger.wandb.tags=['classification+compare']


# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.2
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.25
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.35
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.4
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.45
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.5
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.55
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.6
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.65
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.7
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.75
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.8
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.85
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.90
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.95
# python ../test.py model=voting.yaml logger.wandb.project='colon' trainer.devices=[1] datamodule=colon.yaml logger.wandb.tags=['voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-01_18-07-45/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=1.0

# python ../test.py model=savefeatures.yaml logger=none trainer.devices=[1] datamodule=colonall_feature.yaml ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/colon/classifycompare/2022-08-08_20-11-18/checkpoints/epoch_001.ckpt"
# python ../test.py model=savefeatures.yaml logger=none trainer.devices=[2] datamodule=prostate_feature.yaml ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/prostate/classifycompare/2022-08-09_10-34-32/checkpoints/epoch_005.ckpt"
# python ../test.py model=savefeatures.yaml logger=none trainer.device] datamodule=havard_feature.yaml ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/2022-08-11_13-27-50/checkpoints/epoch_007.ckpt"
# python ../test.py model=savefeatures.yaml logger=none trainer.devices=[4] datamodule=ubc_feature.yaml ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-26_17-43-19/checkpoints/epoch_007.ckpt"



# python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.2  model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.25 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.3 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.35 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.4 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.45 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.5 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.55 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.6 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.65 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.7 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.75 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.8 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.85 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.90 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=0.95 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','ent','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='ent' model.threshold=1.0 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.5 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.55 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.6 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.65 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.7 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.75 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.8 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.85 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.9 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=0.95 model.sampling='random'
python ../test.py datamodule.data_ratio=0.1 model=voting.yaml logger.wandb.project='havard' trainer.devices=[2] datamodule=havard.yaml logger.wandb.tags=['voting','prob','10%'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/harvard/classifycompare/vit_large_r50_s32_384/2022-08-23_12-21-37/checkpoints/epoch_008.ckpt" model.key='prob' model.threshold=1.0 model.sampling='random'

