# python ../train.py logger.wandb.tags=['only_classify'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=16 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=\'0,4,5,6,7\'
# python ../train.py logger.wandb.tags=['only_classify'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=32 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=\'0,4,5,6,7\'

# python ../train.py model=ubc.yaml logger.wandb.tags=['classify+compare'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=16 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=\'0,4,5,6,7\'
# python ../train.py model=ubc.yaml logger.wandb.tags=['classify+compare'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=32 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=\'0,4,5,6,7\'


# python ../test.py model=classify4.yaml datamodule=havard.yaml logger.wandb.tags=['only_classify','harvard'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=16 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=\'1,2\' ckpt_path='/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-26_14-00-38/checkpoints/epoch_006.ckpt'
# python ../test.py model=classifycompare.yaml datamodule=havard.yaml logger.wandb.tags=['classify+compare','harvard'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=16 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=\'4,5,6\' ckpt_path='/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-26_17-43-19/checkpoints/epoch_007.ckpt'
# python ../test.py model=voting.yaml datamodule=havard.yaml logger.wandb.tags=['voting','harvard'] model.scheduler='CosineAnnealingLR' datamodule.num_workers=0 datamodule.batch_size=16 trainer.devices=\'0,4,5,6,7\' logger.wandb.project='ubc' trainer.devices=[1,2,3] ckpt_path='/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-26_17-43-19/checkpoints/epoch_007.ckpt'


# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.2  model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.25 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.3 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.35 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.4 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.45 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.5 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.55 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.6 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.65 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.7 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.75 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.8 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.85 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.90 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=0.95 model.sampling='trust'
# python ../test.py model=voting.yaml logger.wandb.project='ubc' trainer.devices=[5,6,7] datamodule=ubc.yaml logger.wandb.tags=['score_all','voting','ent'] ckpt_path="/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/ubc/classifycompare/2022-08-11_13-33-48/checkpoints/epoch_012.ckpt" model.key='ent' model.threshold=1.0 model.sampling='trust'




#'/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-26_14-00-38/checkpoints/epoch_006.ckpt'
# ubc only classify

#'/home/compu/jh/project/colon_compare/scripts/logs/experiments/runs/default/2022-07-26_17-43-19/checkpoints/epoch_007.ckpt'
# ubc classify+compare


# python ../train.py model=classify4.yaml datamodule=ubc.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='ubc' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6\'
# python ../train.py model=classifycompare.yaml datamodule=ubc.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='ubc' logger.wandb.tags=['classify+compare'] datamodule.num_workers=8 trainer.devices=\'4,5,6\' 

# python ../train.py model=classify4.yaml datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['only_classify'] datamodule.num_workers=8 trainer.devices=\'4,5,6\'
# python ../train.py model=classifycompare.yaml datamodule=colon.yaml model.scheduler='CosineAnnealingLR' logger.wandb.project='colon_new' logger.wandb.tags=['classify+compare'] datamodule.num_workers=8 trainer.devices=\'4,5,6\' 
